version: '3.8'
services:
  reactjs:
    build:
      dockerfile: Dockerfile
      context: client/
    ports:
      - "3000:3000"
  nodejs:
    build:
      dockerfile: Dockerfile
      context: server/
    ports:
      - "3001:3001"

